# Generated by Django 6.0.1 on 2026-01-12 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("rollno", models.IntegerField(default=0)),
                ("contact", models.CharField(default="0000000000", max_length=15)),
            ],
        ),
    ]
